### ISSUE TITLE
You can set the "score" line numbers to be line value?

### ISSUE THREAD

**Issue by Sitmobedaf** [MrMicky-FR/FastBoard#13]
Line numbers (-1, -2, -3, etc.) look ugly. I would like these numbers to be values, but the code is confusing and very tightly coupled for compression.

**Comment by MrMicky-FR** [comment]
Hi, no it’s not possible currently, but for this using directly the Bukkit scoreboard API should be enough, as there is no flickering issue because only the score is updated.
