### ISSUE TITLE
Objectives and below_name Collision

### ISSUE THREAD

**Issue by iFeliN3x0** [MrMicky-FR/FastBoard#15]
Hi, good day.

To summarize, I have a problem and as you read in the title, there is a collision between your API and the minecraft scoreboard objectives, in this case with below_name display slot. This is my code:
```
public static void showHealthbar(Player p, Main plugin) {

	if(p.getScoreboard() == null) {
		p.setScoreboard(Bukkit.getScoreboardManager().getNewScoreboard());
	}
			
	if(p.getScoreboard().getObjective("Health") != null) {
		p.getScoreboard().getObjective("Health").unregister();		
	}
			
	Objective healthbar = p.getScoreboard().registerNewObjective("Health", "health");
	healthbar.setDisplaySlot(DisplaySlot.BELOW_NAME);
			
	p.getScoreboard().getObjective("Health").setDisplayName(ChatColor.translateAlternateColorCodes('&', &b❤));
		
}
```

The problem is that when I use this method with a player, all online players see the same and that should not happen (I mean that only that player should see other players with the blue heart, nevertheless all players see the heart in blue) In the old API that I used, this didn't happen for that am sure that this is a compatibility problem of FastBoard.

So... How can I fix it? Or can you fix it?

**Comment by iFeliN3x0** [comment]
Do you know what am I talking about? Otherwise I can attach some pictures.

**Comment by iFeliN3x0** [comment]
Bump? xd

**Comment by MrMicky-FR** [comment]
I will take a look when I have some time, no need to bump twice in 48h

**Comment by iFeliN3x0** [comment]
That is okay, thank you beforehand

**Comment by MrMicky-FR** [comment]
Does the issue still happens without FastBoard ? And are you sure each player have a different scoreboard ? 
Because if `p.getScoreboard() == null` is false, it will use the current player's scoreboard, and if it's the same for all players (maybe an other plugin?) it will cause this issue. But I don't see how it would be related to FastBoard, as everyting is at packet level, so the Bukkit scoreboard is never used or changed

**Comment by iFeliN3x0** [comment]
Yeah, you were right haha. It was a problem of bukkit scoreboards and it is now solved, thank you!
