### ISSUE TITLE
Character limit questions / feature request

### ISSUE THREAD

**Issue by MAXOUXAX** [MrMicky-FR/FastBoard#16]
My server is running `Paper 1.17`, coupled with `ViaVersion` and `ViaBackwards` to support versions from `1.9` through `1.17.`
When I connect to the server using a version older than `1.13,` my scoreboard lines are cut off, but I'm pretty sure my lines are less than 30 characters long.

**Does this limit include color codes?**

While this limit cannot be circumvented, it would be great to have a **feature allowing to switch to a smart mode** when creating a `FastBoard` instance, a smart mode **that would allow a line longer than 30 characters to be split across multiple lines** while keeping the color code when sending data to past `1.13` versions?
This would keep the display unchanged for versions newer than `1.12` while still allowing older versions to display all desired data.

**Comment by MrMicky-FR** [comment]
Hi,
It’s because the prefix limit on older versions is limited to 16 characters.
To solve this issue you can override the method `hasLinesMaxLength` to return true if the player is on an older server version (or you can also always return true), like this:
```java
FastBoard board = new FastBoard(player) { 
    @Override
    public boolean hasLinesMaxLength() {
        return Via.getAPI().getPlayerVersion(getPlayer()) < ProtocolVersion.v1_13.getVersion(); // or just return true;
    }
});
```
With this the line limit will be 30 characters (with colors) for older versions

**Comment by MAXOUXAX** [comment]
Thanks, although I don't know why you don't include it directly in the library, even without using the ViaVersion API since it just limits the line length for older versions for no apparent reason.

**Comment by MrMicky-FR** [comment]
It’s because with this the line length is limited to 30 chars, so it would set a limit for all 1.13+ servers, even if ViaBackwards isn’t installes

**Comment by MAXOUXAX** [comment]
I believe there's a bug then, because the lines are not 30 characters long, but still truncated on < 1.13.

1.16:
![image](https://share.lyorine.com/files/DkC7IW3vi2HugYV.png)
1.12:
![image](https://share.lyorine.com/files/XIlyw8LOnCNctq9.png)

"&7Événement: &dNexus" is 20 characters long **INCLUDING** color codes

**Comment by AlonsoAliaga** [comment]
Happens to me too when using the system in a new mc version but players connect with older version.
Any way to fix this problem or it's a ViaBackward thing?

**Comment by MrMicky-FR** [comment]
Try to follow the solution from this comment: https://github.com/MrMicky-FR/FastBoard/issues/16#issuecomment-876377553. And if you still have the issue try with just `return true;` in `hasLinesMaxLength`

**Comment by AlonsoAliaga** [comment]
I'll test it, I'm currently using a modified version of your system as I don't want to throw errors if line is longer than 32 chars in old versions. I created a variable called 
`hasMaxLengthLimit (default true)`
in FastBoard constructor i use
`        if(hasViaVersionSupport) {
            playerHasMaxLengthLimit = Via.getAPI().getPlayerVersion(player) < ProtocolVersion.v1_13.getVersion();
        }`
and in the code inside
`private void sendTeamPacket(int score, TeamMode mode) throws Throwable {`
i use
`int maxLength = hasLinesMaxLength() && playerHasMaxLengthLimit ? 16 : 1024;`

I hope it makes sense, I'll test later and let you know

**Comment by MAXOUXAX** [comment]
Can confirm the problem is solved.
Closing the issue now.
