### ISSUE TITLE
Line is longer than 30 chars

### ISSUE THREAD

**Issue by andrei923** [MrMicky-FR/FastBoard#2]
Hello I'm switching from titlemanager to FastBoard but it throws this error

`method FastBoard#updateLines called with ... threw a IllegalArgumentException: Line 10 is longer than 30 chars`

Lines
```
            - '&7{now}
            - ''
            - '&8▪ &fNext Border: &a100'
            - '&8▪ &fPlayers left &a100/100'
            - '&8▪ &fKills &a{kills}'
            - ''
            - '    {up}'
            - ' {left}  {right} &fPlay zone'
            - '    {back}    {status}'
            - ''
            - '&c❤ &e{health} &f{player} &7(You)'
            - ''
            - '&8▪ &fSize {size}x{size}m'
            - ''
            - '&eplay.my-cool-server.net'
```

**Comment by MrMicky-FR** [comment]
Hello, as the error said the line 10 is longer than 30 characters, and the lines are limited to 30 characters with FastBoard

**Comment by andrei923** [comment]
ok, would be really cool if you can make it work with more chars (with titlemanager I was able to use the lines from above)

**Comment by MrMicky-FR** [comment]
I'll see if I can add a higher limit.

**Comment by andrei923** [comment]
Thank you!

**Comment by A248** [comment]
Hey, I was wondering if you could add support for 30 characters as well. Perhaps [this old library](https://github.com/TigerHix/ScoreboardLib) could be useful to show how to add more characters? (It has support for 48 characters on 1.8.8).

I would really like to use FastBoard, since it is much more lightweight due to being packet-based. Hopefully this can be added soon :)

**Comment by MrMicky-FR** [comment]
> Hey, I was wondering if you could add support for 30 characters as well. Perhaps this old library could be useful to show how to add more characters? (It has support for 48 characters on 1.8.8).

From what I can see this library add more characters by using the player name, but this can create flicker since you need to remove and add the player to update the line.
