### ISSUE TITLE
1.18 update

### ISSUE THREAD

**Issue by SkytAsul** [MrMicky-FR/FastBoard#21]
The https://github.com/MrMicky-FR/FastBoard/commit/aeeb871534d0813e96bd2bd44da3e65db4656c44 commit has been released recently to fix an issue with 1.18, but the util version has not changed and nothing has been pushed to maven central.

**Comment by MrMicky-FR** [comment]
Hi, sorry for the delay, I am pretty busy currently, I will publish a new release tomorrow evening

**Comment by SkytAsul** [comment]
That's pretty weird, I can't find the updated artifact on maven central.

**Comment by MrMicky-FR** [comment]
The update is published : http://repo1.maven.org/fr/mrmicky/fastboard/1.2.1/fastboard-1.2.1.jar . But it might take some time before it’s visible

**Comment by MrMicky-FR** [comment]
The update is now available: https://search.maven.org/artifact/fr.mrmicky/fastboard/1.2.1/jar
