### ISSUE TITLE
FastBoard don't exist

### ISSUE THREAD

**Issue by nxyoo** [MrMicky-FR/FastBoard#23]
🇫🇷 
hey! quand je démarre mon serveur, paper me dit que que la classe **```fr.mrmicky.fastboard.FastBoard```** n'existe pas, pourtant je comprend pas j'ai bien importer le plugin dans mes libraries et la classe dans mon main, franchement je suis perdu :/ SI quelqu'un trouve la solution je suis preneur :)

🇬🇧
hi! when i start my server, paper tells me that the class **```fr.mrmicky.fastboard.FastBoard```** don't exist, btw i don't understand because i imported the plugin in my libs and my main.java, if someone could help me it will be cool :)

![image](https://user-images.githubusercontent.com/59174414/161401287-4851d031-b821-4160-bd00-8c21de201da7.png)
![image](https://user-images.githubusercontent.com/59174414/161401295-14e075c8-1f6c-474a-9fa1-6e7f541dfce9.png)

**Comment by MrMicky-FR** [comment]
Par défaut les librairies ajoutées sur IntelliJ ne sont pas incluses dans le jar final. Le plus propre serait d’utiliser Maven/Gradle, mais sinon normalement il est aussi possible de configurer IntelliJ pour que FastBoard soit exporté dans le jar final (dans les paramètres de l’artifact). Mais cette seconde solution ne permet pas de relocaliser FastBoard, ce qui peut causer des problèmes si plusieurs plugins utilisent des versions différentes de FastBoard

**Comment by nxyoo** [comment]
okay merci beacoup!
