### ISSUE TITLE
Does not Exist

### ISSUE THREAD

**Issue by Rl242Dev** [MrMicky-FR/FastBoard#27]
Hi,

Even after searching through the issue #23 I still couldn't install it using Maven and .jar directly
In pom.xml

`
<relocations>
     <relocation>
          <pattern>fr.mrmicky.fastboard</pattern>
          <shadedPattern>com.yourpackage.fastboard</shadedPattern>
     </relocation>
</relocations>
<createDependencyReducedPom>false</createDependencyReducedPom>
`
(I cant wrap it in a code block it bugs)

`

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.8.8-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>fr.mrmicky</groupId>
            <artifactId>fastboard</artifactId>
            <version>1.2.1</version>
        </dependency>
    </dependencies>
`

![image](https://user-images.githubusercontent.com/74558778/221420727-7c5fd09b-0a89-4a3e-ad69-781ae57f0714.png)
![image](https://user-images.githubusercontent.com/74558778/221420750-4cf0778c-6aae-4408-97a2-59f1d88812d7.png)
![image](https://user-images.githubusercontent.com/74558778/221420757-2da77fb4-737d-4a20-8af8-596f91aef18b.png)
![image](https://user-images.githubusercontent.com/74558778/221420769-f0b8dd4e-e9b6-42e9-90b7-ae492a72fe80.png)

If someone could help me

**Comment by MrMicky-FR** [comment]
You need to build your IntelliJ project using Maven and not the built-in IntelliJ compiler

**Comment by Rl242Dev** [comment]
Seems not to work also

**Comment by Rl242Dev** [comment]
[FR]

Mon build plugin sortait au mauvais endroit et donc je n'avais pas la bonne version de mon plugin sur mon Serveur.
Il faut build avec Maven et pas Intellij.
(Maven -> LifeCycle -> Package)

[EN]

My plugin build (Maven) was pointed in another folder than my Intellij builder, so I had the wrong version of my plugin in my Server.
You'll need to build using Maven and not Intellij
(Maven -> LifeCycle -> Package)
