### ISSUE TITLE
Dependency 'fr.mrmicky:fastboard:1.2.1' not found 

### ISSUE THREAD

**Issue by walshy4007** [MrMicky-FR/FastBoard#30]
I've **VERY** new to programming, however in my pom.xml file I'm having issues getting the fastboard integration (I am using Maven)

Link to my pom: https://gist.github.com/walshy4007/26fc2f14221f46374962e571f7722246

Please can you help me know what I'm doing wrong here :(

**Comment by Rl242Dev** [comment]
Solved on WOK, you can close @walshy4007
