### ISSUE TITLE
If temporary overridden, scoreboard is hiding

### ISSUE THREAD

**Issue by TechsCode** [MrMicky-FR/FastBoard#31]
Hey!
We are using FastBoard in our Plugin Ultra Scoreboards and I have a question you may can answer:

If a plugin temporary shows a scoreboard like a minigame plugin, what is the best way to detect the behavior
as soon as the fastboard can get activated again?

Thanks and greetings
Timo

**Comment by MrMicky-FR** [comment]
Hi, this depends on how the mini-game plugin is showing the scoreboard and isn’t related to FastBoard. But the easiest solution would be to see if the plugin provides events to listen to the desire behavior.

it could also be possible by listening outgoing scoreboard packets but it would be pretty performance heavy for this use case
