### ISSUE TITLE
Mojang mappings support

### ISSUE THREAD

**Issue by KonusIntelliJ** [MrMicky-FR/FastBoard#32]
Hey, are u planning support plugin FastBoard for Folia (core)?

**Comment by MrMicky-FR** [comment]
Hi, FastBoard should already be compatible with Folia as everything is packet-based, so no interactions with the scheduler or the world. But if there any issues with Folia, please give the details here

**Comment by KonusIntelliJ** [comment]
![image](https://github.com/MrMicky-FR/FastBoard/assets/62984001/e87c9306-37d4-44f5-8b79-2eecba1d9ffc)

**Comment by KonusIntelliJ** [comment]
![image](https://github.com/MrMicky-FR/FastBoard/assets/62984001/66eedb2a-acd0-49c4-a667-7830c31e26fa)

**Comment by KonusIntelliJ** [comment]
I use Mojang patch version folia. It has only Player (Not EntityPlayer)
![image](https://github.com/MrMicky-FR/FastBoard/assets/62984001/590448d2-d777-4dc4-87ec-63ae8445f25d)

**Comment by KonusIntelliJ** [comment]
> Hi, FastBoard should already be compatible with Folia as everything is packet-based, so no interactions with the scheduler or the world. But if there any issues with Folia, please give the details here

bump

**Comment by MrMicky-FR** [comment]
Hi, after some quick testing it seems like the issue is with the Mojang mappings version of Paper/Folia and not with Folia itself, using the standard Folia version should solve the issue.

I might add Mojang-mapping support in the future

**Comment by MrMicky-FR** [comment]
> bump

No need to bump, especially after only one hour, please…

**Comment by KonusIntelliJ** [comment]
> Hi, after some quick testing it seems like the issue is with the Mojang mappings version of Paper/Folia and not with Folia itself, using the standard Folia version should solve the issue.
> 
> I might add Mojang-mapping support in the future

Good.
