### ISSUE TITLE
[Suggestion] Show original scoreboard

### ISSUE THREAD

**Issue by ShaneBeee** [MrMicky-FR/FastBoard#36]
I would like to suggest a method or something where we could resend the player's original scoreboard if a FastBoard is disabled.

It would be nice if for some reason I am disabling a FastBoard for a player, the player can see their original server (or Bukkit) scoreboard.
This may be useful if I am using a scoreboard for just a mini game or something, and when the player is done the game they would see whatever scoreboard they previously had.

Thanks

**Comment by MrMicky-FR** [comment]
Hi, thank you for this suggestion, this would be a nice feature but I don’t see how it could be implemented, as it would require to listen to outgoing scoreboard packets which would be pretty resource intensive. But any feedback is welcome

**Comment by ShaneBeee** [comment]
Ahh dang, well thanks for letting me know!

**Comment by ShaneBeee** [comment]
1.5 years later, I was able to fix this on my end.
I just force resend the vanilla scoreboard to the player.

I had to send a dummy one first as CraftBukkit stops you from sending the same scoreboard.
<img width="736" alt="Image" src="https://github.com/user-attachments/assets/46f61d37-0b5e-41bf-b12d-2518da877c55" />
