### ISSUE TITLE
Release 1.20.2 on maven central :)

### ISSUE THREAD

**Issue by SkytAsul** [MrMicky-FR/FastBoard#40]

**Comment by SkytAsul** [comment]
I just tested the latest commit on 1.20.2, it works perfectly!

**Comment by MrMicky-FR** [comment]
I've just released v2.0.1 on Maven Central, it should be available shortly

**Comment by MrMicky-FR** [comment]
Version 2.0.1 is now available on Maven Central: https://central.sonatype.com/artifact/fr.mrmicky/fastboard/2.0.1
