### ISSUE TITLE
Add support for Minecraft 1.20.3

### ISSUE THREAD

**Issue by DevMango555** [MrMicky-FR/FastBoard#42]
Hello,

Minecraft 1.20.3 is out, this version modifies the Scoreboard.
So I noticed that the Scoreboard appears, but without the lines...

The following exception occurs:
`java.lang.RuntimeException: Unable to update scoreboard lines` [updateLines()](https://github.com/MrMicky-FR/FastBoard/blob/a9b5019b87c2c4f4c837ea4c4357ab506db99efd/src/main/java/fr/mrmicky/fastboard/FastBoardBase.java#L315)

by calling the [sendScorePacket()](https://github.com/MrMicky-FR/FastBoard/blob/a9b5019b87c2c4f4c837ea4c4357ab506db99efd/src/main/java/fr/mrmicky/fastboard/FastBoardBase.java#L472)

Cause of exception:
`Caused by: java.lang.IllegalAccessException: Can not set final java.lang.String field net.minecraft.network.protocol.game.PacketPlayOutScoreboardScore.a to java.lang.String`

The method #sendScorePacket() will invoke the PACKET_SB_SCORE by allocating the necessary fields.
Except that the PacketPlayOutScoreboardScore has changed: it's no longer a class, but a record.

I didn't see any other changes, but regarding issue #41, when an Objective is created, a new parameter is present.

Honestly, this issue is here to point out that the library doesn't work (at least for me) in version 1.20.3, after which I didn't really investigate any further.

Hopefully it was useful and not the other way around ;)

**Comment by MrMicky-FR** [comment]
1.20.3 support is available in FastBoard v2.0.2 👍
