### ISSUE TITLE
Increase Adventure components line length on legacy servers

### ISSUE THREAD

**Issue by MayBlock** [MrMicky-FR/FastBoard#45]
![image](https://github.com/MrMicky-FR/FastBoard/assets/49287036/946ccdb6-2a34-47a6-8413-9015e08d8923)

if you use component, maximum content length of the scoreboard can only be 16 characters. but in theory, scoreboard in 1.8 can support a maximum of 32 characters

**Comment by xism4** [comment]
> ![image](https://private-user-images.githubusercontent.com/49287036/290996472-946ccdb6-2a34-47a6-8413-9015e08d8923.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyOTQ5MzMsIm5iZiI6MTcxNTI5NDYzMywicGF0aCI6Ii80OTI4NzAzNi8yOTA5OTY0NzItOTQ2Y2NkYjYtMmEzNC00N2E2LTg0MTMtOTAxNWUwOGQ4OTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDIyNDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljZmE0MWZhMGQ2YWI2YmQ1YjMxNWFiZmYyMDU3M2JiMGM0NDI0NmMyN2M4N2NjNGQ1MGFiNjUxMGU3MmY3YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c3dHD1-6T9FK0ByoiVLVXa6yzCSIZUCqSHzMT5EqRD0)
> 
> if you use component, maximum content length of the scoreboard can only be 16 characters. but in theory, scoreboard in 1.8 can support a maximum of 32 characters

Bump for this?

**Comment by MrMicky-FR** [comment]
> Bump for this?

As of today, 1.8.8 is still perfectly supported by the non-Adventure version, despite being [almost 9 years old](https://howoldisminecraft188.today/), so adding features to such an outdated version is far from a priority.

Also, in general, please avoid bumping issues on GitHub projects as it doesn't help, but please consider making a pull request instead :)

**Comment by MrMicky-FR** [comment]
After some thought, I will close this for now: as mentioned in my previous comment, legacy versions are really old, even [Minecraft 1.12.2 is almost 7 years old](https://how-old-is-mc.today/1.12.2), and supporting longer lines on these legacy versions would require too many changes, so newer versions should definitely be considered.

Most importantly, long lines on legacy versions are **fully supported by the non-Adventure** version, which can be used if legacy support cannot be dropped.
