### ISSUE TITLE
[Paper 1.20.4] Custom Scores incompatibles for Players < 1.20.4 (Log error)

### ISSUE THREAD

**Issue by x9nico** [MrMicky-FR/FastBoard#48]
Hello,

J'ai tenté d'expérimenter l'implémentation dans FB les scores persos.
Lorsque l'on utilise les scores custom de la 1.20.4, un joueur en version < se voit déconnecter de manière instantanée du serveur, et provoque une erreur dans la console avec ViaVersion + ViaBackwards.

Ne serait-il pas possible de "prévenir" ces cas de joueurs lors de l'usage de cette feature pour les joueurs < à la 1.20.4 ?

Voici le message d'erreur :

https://hastebin.com/share/kixufikawu.markdown

**[EDIT 01/03/24] :** J'ai tenté sans avoir les scores custom (avec la suppression de l'affichage des scores), ça fait quand même le message d'erreur. Je pense que ViaVersion + VB ne supporte pas ça ?

**Comment by MrMicky-FR** [comment]
Même réponse que pour #24, en testant je n’avais pas le problème et il faudrait donc un exemple minimal pour reproduire cette issue avec les numéros de build de Paper/VV/VB 🙂

Mais sinon à part si FastBoard envoie un packet qui ne respecte pas le protocole de la 1.20.4 (ce qui m’étonnerait, mais pas impossible), le problème sera à corriger du côté de ViaBackwards

**Comment by x9nico** [comment]
> Même réponse que pour #24, en testant je n’avais pas le problème et il faudrait donc un exemple minimal pour reproduire cette issue avec les numéros de build de Paper/VV/VB 🙂
> 
> Mais sinon à part si FastBoard envoie un packet qui ne respecte pas le protocole de la 1.20.4 (ce qui m’étonnerait, mais pas impossible), le problème sera à corriger du côté de ViaBackwards

J'ai effectué un exemple pour un joueur qui se connecte en 1.9.4 (oui je suis un peu taré xD) sur un serveur Paper 1.20.4 dernier build (Build N°436).

Pour les plugins VV & VB j'ai les versions suivantes : 
![image](https://github.com/MrMicky-FR/FastBoard/assets/8091015/4af2207e-6fce-4048-b008-a67411533558)

**Comment by MrMicky-FR** [comment]
> En testant je n’avais pas le problème et il faudrait donc un exemple minimal pour reproduire cette issue

ViaVersion et ViaBackwards ne sont pas à jour, les dernières versions (disponibles sur le CI de ViaVersion) corrigent le problème :
- ViaVersion : https://ci.viaversion.com/job/ViaVersion/
- ViaBackwards : https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/
