### ISSUE TITLE
A method for getting Scoreboard

### ISSUE THREAD

**Issue by xeRicker** [MrMicky-FR/FastBoard#49]
Hello, I'm planning to use FastBoard, but I would greatly appreciate a method to acquire FastBoard's Bukkit scoreboard so I can create teams and manage them. I've looked over the API, and it seems like FastBoard doesn't offer a way to get the scoreboard it creates.

**Comment by MrMicky-FR** [comment]
FastBoard doesn’t use the Bukkit scoreboard at all, you can create a Bukkit scoreboard in your plugin if needed

**Comment by xeRicker** [comment]
Thank you for pointing that out. I've taken a different approach and it's working great with your API :D
