### ISSUE TITLE
Tab list?

### ISSUE THREAD

**Issue by Electroid** [MrMicky-FR/FastBoard#5]
This is a really great library, thanks for making it "thin" and easy to use. Would you consider adding support or making another library for tab list support?

**Comment by MrMicky-FR** [comment]
Hi, yes it could a be nice feature, but just what would be the benefits of doing it with packets instead of using the Bukkit API (creating scoreboard teams with the Bukkit API or just using Player#setPlayerListName) ?

**Comment by ImNotStable** [comment]
I feel like it'd be helpful so that we can use features that [TAB](https://github.com/NEZNAMY/TAB/) has without using the plugin and configuring it. So we could easily set up tab list sorting, create multiple above/below name lines, have "infinite length" names, and the many other features it has.

I don't think it should be packaged with FastBoard, as not everyone using FastBoard wants to have tab utility.

**Comment by jordoncodes** [comment]
(im not experienced with this) but I believe using packets instead of the Bukkit API allows for having less conflicts with other plugins? Idk but I remember seeing plugins saying that's why they use packets.

**Comment by ImNotStable** [comment]
Is it possible for you to create an API to be able to do so?

**Comment by jordoncodes** [comment]
> Is it possible for you to create an API to be able to do so?

I could send code to send tablist prefix/suffix, essentially a builder for a packet; using NMS or protocollib if u want, add me on discord: onlyjordon

**Comment by xism4** [comment]
> > Is it possible for you to create an API to be able to do so?
> 
> I could send code to send tablist prefix/suffix, essentially a builder for a packet; using NMS or protocollib if u want, add me on discord: onlyjordon

You are 

> Hi, yes it could a be nice feature, but just what would be the benefits of using a lib instead of using the Bukkit API (creating scoreboard teams with the Bukkit API or just using Player#setPlayerListName) ?

Other plugins may conflict, using NMS would be the best way. An API could make it much simpler for new developers to use.

**Comment by MrMicky-FR** [comment]
> Other plugins may conflict, using NMS would be the best way. An API could make it much simpler for new developers to use.

I think it’s important to note that currently Minecraft internals are moving faster than ever, with breaking changes basically every two minor releases, so I would strongly recommend using Bukkit API when possible. And using Bukkit API for Teams/tablist with a packet-based scoreboard (like FastBoard) wouldn’t conflict

**Comment by MrMicky-FR** [comment]
Hello, after a lot of thought I think that managing the tab list in FastBoard would not be a good solution. In fact, unlike the scoreboard (sidebar), the tablist can very easily be managed with Bukkit `Team`s, while being compatible with FastBoard.

Also, in recent versions of Minecraft, Mojang has very often made changes to the scoreboard protocol, which means that FastBoard has to be updated very often, so I don't think that using NMS even more is a good solution. Ideally, FastBoard shouldn't use NMS either (at least for recent versions), but that doesn't seem possible today with the existing API.
