### ISSUE TITLE
Minecraft 1.21 Support

### ISSUE THREAD

**Issue by frafol** [MrMicky-FR/FastBoard#56]
It doesn't seem to work with Spigot 1.21.

**Comment by MrMicky-FR** [comment]
Tested on Spigot 1.21 with vanilla Minecraft 1.21 client and it's working fine for me. Otherwise please include details on how to reproduce the issue (minimal test code, console errors if any, test conditions, etc) rather than just saying "doesn't seem to work"

**Comment by frafol** [comment]
ohh nvm the plugin is using an older version of the ap I only noticed it now
