### ISSUE TITLE
Failed to register events for class Main because fr/mrmicky/fastboard/FastBoard does not exist.

### ISSUE THREAD

**Issue by waleeedkhalid** [MrMicky-FR/FastBoard#59]
Error: ```Failed to register events for class me.waleeed.main.Main because fr/mrmicky/fastboard/FastBoard does not exist.```
as it's shown I have this error while starting the server, the code is like the example code

Paper: 1.20.6
Java: 21

And I have put it in the artifacts of build(Using IntelliJ)

**Comment by MrMicky-FR** [comment]
You are not shading correctly FastBoard, you should use Maven/Gradle with the example config in the README

**Comment by waleeedkhalid** [comment]
I'm sure that shading is work
```[INFO] Replacing original artifact with shaded artifact.```
and the question is what should be the edited is it a class or just the package to main class ?

**Comment by waleeedkhalid** [comment]
I mean instead of fr.mrmicky.fastboard I will replace fr.mrmicky with my package and fastboard is a package that not exist in my project

**Comment by MrMicky-FR** [comment]
Maven/Gradle takes care of the relocation
