### ISSUE TITLE
Failed to register events for class ... because fr/mrmicky/fastboard/FastBoard does not exist.

### ISSUE THREAD

**Issue by BySplashGm** [MrMicky-FR/FastBoard#62]
Error: `Failed to register events for class fr.bysplash.splashblock.util.Scoreboard because fr/mrmicky/fastboard/FastBoard does not exist.`
Is shown in console on plugin load

Paper: 1.21.1
Java: 21

Maven pom.xml has what readme said to do

**Comment by MrMicky-FR** [comment]
You have an issue during plugin compilation. Please send the pom.xml here or on Discord, and also make sure to use the JAR file in the `target` folder, and not in the `out` folder for example
