### ISSUE TITLE
Add support for Adventure Components

### ISSUE THREAD

**Issue by hawkfalcon** [MrMicky-FR/FastBoard#7]
This looks perfect, lightweight and just an API, should be built into Paper.

Would it be possible to integrate either the Adventure Components API or MiniMessage support into the plugin?

Thanks!

**Comment by Jpac14** [comment]
+1

**Comment by MrMicky-FR** [comment]
> +1

Hi, no need to bump like this as it doesn’t help. Please use the reactions instead.

About the original suggestion, it would require to add a separate module with Adventure support, and I think it wouldn’t be easy to serialize Adventure components to NMS components while keeping 1.7.10 to 1.17 support in a reasonable size, but I will try to work on it when I have some time.

Also as a (not very clean) workaround until Adventure support is added, you can use the LegacyComponentSerializer to convert Adventure components to strings (and scoreboard doesn’t supports click/hover events so everything should work)

**Comment by Authorises** [comment]
Any updates on this?

**Comment by MrMicky-FR** [comment]
> Any updates on this?

No, no need to bump it doesn’t help, please see my above reply

**Comment by MrMicky-FR** [comment]
A beta version of FastBoard v2.0, which adds support for Adventure components is on the pull-request #29 🚀 Feel free to comment about these changes on the pull request :)

**Comment by MrMicky-FR** [comment]
Adventure components are now supported with version 2.0.0 of FastBoard ! And btw Minecraft 1.20 is also supported
