### ISSUE TITLE
Custom index

### ISSUE THREAD

**Issue by AlonsoAliaga** [MrMicky-FR/FastBoard#9]
Hello, is it possible that you modify the system to allow custom number (the one in red) like in the minigames?
![16177496252476885988035475347836](https://user-images.githubusercontent.com/36780081/113787703-20717500-9701-11eb-8d15-668586c2f703.jpg)

**Comment by MrMicky-FR** [comment]
Hi, it would need to change a big part of FastBoard, and IMHO it's easier and looks better to just display the score next to the team (you don't need to mess with negative numbers and you can easily add other lines above the score) like this:
![fastboard](https://user-images.githubusercontent.com/30863452/113826810-e052d680-9782-11eb-8e7c-6e78bfaa9027.png)
